# Generated by Django 4.1.6 on 2023-03-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product gallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
